const tiers = [
  {
    tier: 0,
    name: "Free",
    price: 0,
    basicCap: 0,
    premiumCap: 0,
    brandedContent: false,
    rewardedContent: false,
    analyticsTier: 0,
  },
  {
    tier: 1,
    name: "Premium",
    price: 50,
    basicCap: 10000,
    premiumCap: 0,
    brandedContent: false,
    rewardedContent: false,
    analyticsTier: 0,
  },
  {
    tier: 2,
    name: "Elite",
    price: 199,
    basicCap: Infinity,
    premiumCap: 5000,
    brandedContent: true,
    rewardedContent: true,
    analyticsTier: 1,
  },
  {
    tier: 3,
    name: "Ultimate",
    price: 499,
    basicPricePerPlay: 0,
    premiumCap: 50000,
    brandedContent: true,
    rewardedContent: true,
    analyticsTier: 2,
  },
  {
    tier: 4,
    name: "Pay As You Go",
    brandedContent: true,
    rewardedContent: true,
    isPayg: true,
    basicPricePerPlay: 0,
  },
];

export const getSubscriptionType = (tier) => tiers[tier];
