export class Images {
  static data = {
    arrow: "arrow.png",
    arrow_flip: "arrow_flip.png",
    tutorial_continue:"tutorial_continue.png",
    arrow_up: "arrow_up.png",
    background: "background.jpg",
    ball: "af_ball.jpg",
    barrel: "barrel.jpg",
    barrel_up: "barrel_up.jpg",
    biggerBall: "biggerBall.png",
    blackbg: "blackbg.png",
    blackbg1: "blackbg1.png",
    blackbg2: "blackbg2.png",
    blackbg3: "blackbg3.png",
    blackbg4: "blackbg4.png",
    Booster05: "Booster05.png",
    can_up: "can_up.jpg",
    CenterStar: "CenterStar.png",
    CloseBtn: "CloseBtn.png",
    danger_transparent: "danger.png",
    enemy: "enemy.jpg",
    Energy: "Energy.png",
    flare: "flare.png",
    greengrass: "greengrass.jpg",
    hand: "hand.png",
    Handler: "Handler.png",
    heart: "heart.png",
    Hourglass: "Hourglass.png",
    items_bg: "items_bg.png",
    LeftStar: "LeftStar.png",
    logo1: "logo1.jpg",
    logo2: "logo2.jpg",
    logo3: "logo3.jpg",
    logo4: "logo4.jpg",
    LosePopup: "LosePopup.png",
    MusicIcon: "MusicIcon.png",
    NextBtn: "NextBtn.png",
    nextlvl_bg: "nextlvl_bg.png",
    pause_button: "pause_button.png",
    PopupBig: "PopupBig.png",
    powerup_credit: "powerup_credit.jpg",
    RightStar: "RightStar.png",
    ring1: "ring1.png",
    ring2: "ring2.png",
    sad: "sad.png",
    SaveBtn: "SaveBtn.png",
    scorebg: "scorebg.png",
    shield: "shield.png",
    SoundIcon: "SoundIcon.png",
    starsBg: "starsBg.png",
    switch: "switch.png",
    switch_base: "switch_base.png",
    thunder: "thunder.png",
    TopPanel: "TopPanel.png",
    ModalHeader:"ModalHeader.png"
  };
}
